#!/bin/bash
#SBATCH --partition=exfel 
#SBATCH --job-name=legacyOut.h5.job
#SBATCH --chdir /gpfs/exfel/data/user/guestt/spb_model/run/NanoKB-FastPulse/ 
#SBATCH --nodes=1
 #SBATCH --output=/gpfs/exfel/data/user/guestt/spb_model/logs/energyAnalysis/legacyOut.h5.out
#SBATCH --error=/gpfs/exfel/data/user/guestt/spb_model/logs/energyAnalysis/legacyOut.h5.err
#SBATCH --time=14-00:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=trey.guest@desy.de
python /gpfs/exfel/data/user/guestt/spb_model/model/analysis/extractEnergyData.py legacyOut.h5
